name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18

      - name: Install Dependencies on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.23.0/tinygo_0.23.0_amd64.deb
          sudo dpkg -i tinygo_0.23.0_amd64.deb

      - name: Install Dependencies on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew tap tinygo-org/tools
          brew install tinygo

      - name: Build on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          make
          ./out/luckypg
          mv out/luckypg out/luckypg-linux

      - name: Build on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          make
          ./out/luckypg
          mv out/luckypg out/luckypg-macos

      - name: Run Tests
        run: make test

      - name: Upload artifacts on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v3
        with:
          path: out/luckypg-linux

      - name: Upload artifacts on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v3
        with:
          path: out/luckypg-macos

  pre-release:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Pre-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            artifact/*
